### ISSUE TITLE
Portugal showing up as not taking part on WLM 2019

### ISSUE THREAD

**Issue by pdarwin** [hatnote/monumental#33]
Portugal showing up as not taking part on WLM 2019 (but we are!) - please fix this ASAP, as the map would be extremely useful for us (we're entirely on Wikidata now)

**Comment by JeanFred** [comment]
Cross-filed as https://phabricator.wikimedia.org/T231760

**Comment by JeanFred** [comment]
I believe this issue applies to https://github.com/hatnote/monumental-wlm

**Comment by yarl** [comment]
Replied on Phab.
Issue ended up here because of link in the footer that needs to be updated.

**Comment by pdarwin** [comment]
Thanks!

**Comment by yarl** [comment]
Closing, will continue on Phab.
